AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create an RDS Instance'

Parameters:
  DBUsername:
    Type: String
    Description: Master username for the RDS instance
  DBPassword:
    Type: String
    NoEcho: true
    Description: Master password for the RDS instance

Resources:
  MyDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: 'MyNewRDS'
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBInstanceClass: 'db.t4g.micro'
      Engine: 'mysql'
      EngineVersion: '8.4.9'
      AllocatedStorage: '20'
      BackupRetentionPeriod: 1